/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

group = "hexlet.code"
version = "1.0-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

plugins {
    id("application")
    id("checkstyle")
    // id("jvm-test-suite")
    id("com.github.ben-manes.versions") version "0.53.0"
    id("io.freefair.lombok") version "9.1.0"
    id("se.patrikerdes.use-latest-versions") version "0.2.19"
    id("com.gradleup.shadow") version "9.3.0"
    // id("org.sonarqube") version "7.2.2.6593"
    // id("jacoco")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

checkstyle {
    toolVersion = "12.3.1"

    configFile = file("../config/checkstyle/checkstyle.xml")

    isIgnoreFailures = true
    maxWarnings = 0
    maxErrors = 0
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

application {
    // Define the main class for the application.
    mainClass.set("hexlet.code.App")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.2")
        }
    }
}
