/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

group = "hexlet.code"
version = "1.0-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

plugins {
    id("application")
    id("checkstyle")
    // id("jvm-test-suite")
    id("org.gradle.plugin-compatibility") version "1.0.0"
    id("com.github.ben-manes.versions") version "0.49.0"
    id("io.freefair.lombok") version "8.1.0"
    id("se.patrikerdes.use-latest-versions") version "0.2.18"
    id("com.gradleup.shadow") version "8.3.10"
    id("org.sonarqube") version "4.0.0.2929"
    id("jacoco")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

checkstyle {
    toolVersion = "10.9.3"

    configFile = file("../config/checkstyle/checkstyle.xml")

    isIgnoreFailures = true
    maxWarnings = 0
    maxErrors = 0
}

jacoco {
    toolVersion = "0.8.12"
}

sonar {
    properties {
        property("sonar.projectName", "Hexlet.Java.m3k.Validator")
        property("sonar.projectKey", "AnrDaemon_java-project-78")
        property("sonar.organization", "anrdaemon")
        property("sonar.host.url", "https://sonarcloud.io")
    }
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    testImplementation("com.ginsberg:junit5-system-exit:2.0.2")
}

application {
    // Define the main class for the application.
    mainClass.set("hexlet.code.App")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.3")

            targets.all {
                testTask.configure {
                    finalizedBy(tasks.jacocoTestReport)

                    jvmArgumentProviders.add(CommandLineArgumentProvider {
                        listOf("-javaagent:${configurations.testRuntimeClasspath.get().files.find {
                            it.name.contains("junit5-system-exit") }
                        }")
                    })
                }
            }
        }
    }
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to application.mainClass.get(),
            "Implementation-Title" to "Validator course work",
            "Implementation-Version" to project.version
        )
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.addAll(arrayOf(
        "-Aproject=${project.group}/${project.name}"
    ))
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        csv.required.set(false)
    }
}

tasks.register("install") {
    dependsOn("installDist")
}
